@base=http://localhost:8080/api


POST {{base}}/Products/addUpdateProducts416 HTTP/1.1
Content-Type: application/json

{
    "name": "Vignessh",
    "mainCat": "test",
    "image":"base64",
    "price": 20.02,
    "desc": "qorking fine",
    "available": true
}

###
GET {{base}}/Products HTTP/1.1

###
GET {{base}}/Products/priceRange HTTP/1.1
